{% set version = "3.8.0" %}

package:
  name: arpack
  version: {{ version }}

source:
  fn: arpack-{{ version }}.tar.gz
  url: https://github.com/opencollab/arpack-ng/archive/{{ version }}.tar.gz
  sha256: ada5aeb3878874383307239c9235b716a8a170c6d096a6625bfd529844df003d

build:
  number: 0
  script:
    - build-mpi.sh  # [not win and mpi != 'nompi']
    - build-no-mpi.sh  # [not win and mpi == 'nompi']
    - bld-no-mpi.bat  # [win]
  run_exports:
    - {{ pin_subpackage('arpack', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - libblas
    - liblapack
    - {{ mpi }}  # [mpi != 'nompi']
  run:
    - {{ mpi }}  # [mpi != 'nompi']

test:
  commands:
    - test -f ${PREFIX}/lib/libarpack.a  # [unix]
    - test -f ${PREFIX}/lib/libarpack${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/include/arpack/arpack.hpp  # [unix]
    - if not exist %PREFIX%\\Library\\mingw-w64\\lib\\libarpack.a exit 1  # [win]
    - if not exist %PREFIX%\\Library\\mingw-w64\\lib\\libarpack.dll.a exit 1  # [win]
    - if not exist %PREFIX%\\Library\\mingw-w64\\bin\\libarpack.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\mingw-w64\\include\\arpack\\arpack.hpp exit 1  # [win]

about:
  home: https://github.com/opencollab/arpack-ng
  license: BSD 3-Clause
  license_file: COPYING
  summary: Fortran77 subroutines designed to solve large scale eigenvalue problems

extra:
  recipe-maintainers:
    - jschueller
